server:
  port: 8080

spring:
  application:
    name: brightpath-service
  datasource:
    url: jdbc:postgresql://localhost:5433/bookingdb
    driver-class-name: org.postgresql.Driver
    username: tommyvo
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
